# Send a Slack release notification.

name: Release Notifications
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      release_tag:
        required: true
        type: string
      release_url:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

# Grant no permissions to this workflow.
permissions: {}

jobs:
  slack:
    name: Slack release notification
    # Remove the next line after your Slack app has been set up. See also:
    # https://github.com/slackapi/slack-github-action#setup-2
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1.5.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Notify via Slack
      uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302 # v1.21.0
      with:
        payload: |
          {
            "text": "${{ inputs.repo_name }} published a new release ${{ inputs.release_tag }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ inputs.repo_name }}* published a new release <${{ inputs.release_url }}|${{ inputs.release_tag }}>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
