# Automatically merge Dependabot PRs upon approval by leaving
# a comment on Dependabot's pull-request.
#
# yamllint disable rule:document-start rule:document-end

name: Automerge Dependabot PR
on: # yamllint disable-line rule:truthy
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  comment:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Merge Dependabot PR
      run: gh pr comment --body "@dependabot squash and merge" "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
