# Automatically merge Dependabot PRs upon approval.

name: Automerge Dependabot PR
on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Merge Dependabot PR
      run: gh pr merge --squash --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
