# This workflow will lint the PR's title and commit message.
# https://github.com/CondeNast/conventional-pull-request-action
# https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md
# https://github.com/CondeNast/conventional-pull-request-action/issues/15

name: Pull Request
on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - edited
      - synchronize
jobs:
  pr:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CondeNast/conventional-pull-request-action@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: "./commitlint.rules.js"
          commitTitleMatch: "true"
  check:
    needs: pr
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[test,dev]
    - name: Run flake8
      run: flake8 src tests
    - name: Run pylint
      run: pylint src tests
    - name: Run mypy
      run: mypy src tests
    - name: Run tox
      run: |
        pip install tox-gh-actions
        tox
