# This workflow publishes Markdown docs to Github Wiki.
# Some manual setup is required before using it:
#   1. Enable Wiki in repository and create at least one page.
#   2. Generate a Personal Access Token (PAT) with "repo" scope enabled.
#   3. Add the generated PAT as a secret named "GH_PERSONAL_ACCESS_TOKEN".
# For details, see https://github.com/marketplace/actions/publish-to-github-wiki#setup
name: Generate Wiki Pages

on:
  release:
    types: [published]

jobs:
  generate-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Set up Python
      uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: make setup
      env:
        PYTHON: python
    - name: Generate Markdown docs
      run: |
        make docs-md
        mv docs/_build/markdown/index.md docs/_build/markdown/Home.md
    - name: Push to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@a87db85ed06e4431be29cfdcb22b9653881305d0
      with:
        path: docs/_build/markdown
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
