# This workflow publishes Markdown docs to Github Wiki. Some manual setup
# is required before using it: enable Wiki in repository and create at least
# one page.

name: Publish Github Wiki
on:
  release:
    types:
    - released
permissions:
  contents: read
env:
  ARTIFACT_NAME: artifact-ubuntu-latest-python-3.10
  # This is the username and email for the user who commits and pushes the
  # Wiki update. In an organisation that should be a dedicated devops account.
  USER_NAME: jenstroeger
  USER_EMAIL: jenstroeger@users.noreply.github.com

jobs:
  publish-wiki:
    name: Publish Github Wiki
    if: github.event.repository.has_wiki == true
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1.5.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    # Check out the repository's Wiki repo into the wiki/ folder. The token is required
    # only for private repositories.
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ format('{0}.wiki', github.repository) }}
        path: wiki

    # It is currently not possible to download the artifacts of another workflow, and
    # that's been an issue for a long time and for many people. For a discussion see
    #
    # https://github.com/actions/download-artifact/issues/3
    #
    # One of the suggested workarounds is to use an alternative action, based on this
    # comment: https://github.com/actions/download-artifact/issues/3#issuecomment-828965675
    # Here too, 'github_token' is required for private repositories.
    - name: Download artifact
      uses: dawidd6/action-download-artifact@e6e25ac3a2b93187502a8be1ef9e9603afc34925 # v2.24.2
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        workflow: release.yaml
        workflow_conclusion: success
        commit: ${{ github.sha }}
        name: ${{ env.ARTIFACT_NAME }}
        path: dist

    # Unpack the Markdown docs into the Wiki repository. Delete existing files first
    # to ensure that no stale files stay behind.
    - name: Copy Markdown documentation
      run: |
        mkdir docs/
        unzip -d docs/ `ls dist/*-docs-md.zip`
        rm --recursive --force wiki/*
        cp --recursive --verbose --target-directory wiki/ docs/markdown/*

    # If there was any change to the Wiki then push the update.
    - name: Push to Wiki
      run: |
        cd wiki/
        if [ -n "`git status --porcelain`" ]; then
          git add .
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git commit --message "$WIKI_COMMIT_MESSAGE"
          git push
        fi
      env:
        WIKI_COMMIT_MESSAGE: |
          docs: update for ${{ github.event.release.tag_name }}

          Refs: ${{ github.sha }}
          Link: ${{ github.event.release.html_url }}
